name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Instalar o Poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: cd backend && poetry install

      - name: Executar os testes
        run: cd backend && poetry run task test